{% set name = "hg-git" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5c5f6f02dbd42b9c913f83b166ff37fc00368dd7b9b7bcdade3aa0cae5dce5e5

build:
  number: 1
  noarch: python
  script: pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - mercurial
    - dulwich >=0.21.6,<0.23.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - hggit
  commands:
    - hg version -v
    - hg debuginstall
    - hg help -e hggit --config "extensions.hggit="

about:
  home: https://wiki.mercurial-scm.org/HgGit
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Push to and pull from a Git repository using Mercurial
  doc_url: https://wiki.mercurial-scm.org/HgGit
  dev_url: https://foss.heptapod.net/mercurial/hg-git/

extra:
  recipe-maintainers:
    - paugier
